
XY_MSG(e_open_file, error, "Unable to open file '%s'. This could be because the file does not exist or because the compiler does not have permission to open the file.")
XY_MSG(w_invalid_utf8_cp, warning, "Encountered an invalid UTF-8 codepoint. The invalid sequence of bytes has been substituted with '%s'.")
XY_MSG(e_invalid_trailing_utf8_cp, error, "Encountered an incomplete UTF-8 codepoint at the end of the file.")
XY_MSG(e_non_graph_char, recoverable_error, "Encountered a non-graphical ASCII character with ordinal '%d'.")

